//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from sdp.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="sdpParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IsdpListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.session_description"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSession_description([NotNull] sdpParser.Session_descriptionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.session_description"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSession_description([NotNull] sdpParser.Session_descriptionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.proto_version"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProto_version([NotNull] sdpParser.Proto_versionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.proto_version"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProto_version([NotNull] sdpParser.Proto_versionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.origin_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrigin_field([NotNull] sdpParser.Origin_fieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.origin_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrigin_field([NotNull] sdpParser.Origin_fieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.session_name_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSession_name_field([NotNull] sdpParser.Session_name_fieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.session_name_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSession_name_field([NotNull] sdpParser.Session_name_fieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.information_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInformation_field([NotNull] sdpParser.Information_fieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.information_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInformation_field([NotNull] sdpParser.Information_fieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.uri_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUri_field([NotNull] sdpParser.Uri_fieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.uri_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUri_field([NotNull] sdpParser.Uri_fieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.email_fields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmail_fields([NotNull] sdpParser.Email_fieldsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.email_fields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmail_fields([NotNull] sdpParser.Email_fieldsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.phone_fields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPhone_fields([NotNull] sdpParser.Phone_fieldsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.phone_fields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPhone_fields([NotNull] sdpParser.Phone_fieldsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.connection_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConnection_field([NotNull] sdpParser.Connection_fieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.connection_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConnection_field([NotNull] sdpParser.Connection_fieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.bandwidth_fields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBandwidth_fields([NotNull] sdpParser.Bandwidth_fieldsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.bandwidth_fields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBandwidth_fields([NotNull] sdpParser.Bandwidth_fieldsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.time_fields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTime_fields([NotNull] sdpParser.Time_fieldsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.time_fields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTime_fields([NotNull] sdpParser.Time_fieldsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.repeat_fields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRepeat_fields([NotNull] sdpParser.Repeat_fieldsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.repeat_fields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRepeat_fields([NotNull] sdpParser.Repeat_fieldsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.zone_adjustments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterZone_adjustments([NotNull] sdpParser.Zone_adjustmentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.zone_adjustments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitZone_adjustments([NotNull] sdpParser.Zone_adjustmentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.key_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKey_field([NotNull] sdpParser.Key_fieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.key_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKey_field([NotNull] sdpParser.Key_fieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.attribute_fields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttribute_fields([NotNull] sdpParser.Attribute_fieldsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.attribute_fields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttribute_fields([NotNull] sdpParser.Attribute_fieldsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.media_descriptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMedia_descriptions([NotNull] sdpParser.Media_descriptionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.media_descriptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMedia_descriptions([NotNull] sdpParser.Media_descriptionsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.media_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMedia_field([NotNull] sdpParser.Media_fieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.media_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMedia_field([NotNull] sdpParser.Media_fieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.username"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUsername([NotNull] sdpParser.UsernameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.username"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUsername([NotNull] sdpParser.UsernameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.sess_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSess_id([NotNull] sdpParser.Sess_idContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.sess_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSess_id([NotNull] sdpParser.Sess_idContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.sess_version"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSess_version([NotNull] sdpParser.Sess_versionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.sess_version"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSess_version([NotNull] sdpParser.Sess_versionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.nettype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNettype([NotNull] sdpParser.NettypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.nettype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNettype([NotNull] sdpParser.NettypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.addrtype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddrtype([NotNull] sdpParser.AddrtypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.addrtype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddrtype([NotNull] sdpParser.AddrtypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.uri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUri([NotNull] sdpParser.UriContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.uri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUri([NotNull] sdpParser.UriContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.email_address"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmail_address([NotNull] sdpParser.Email_addressContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.email_address"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmail_address([NotNull] sdpParser.Email_addressContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.address_and_comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddress_and_comment([NotNull] sdpParser.Address_and_commentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.address_and_comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddress_and_comment([NotNull] sdpParser.Address_and_commentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.dispname_and_address"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDispname_and_address([NotNull] sdpParser.Dispname_and_addressContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.dispname_and_address"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDispname_and_address([NotNull] sdpParser.Dispname_and_addressContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.phone_number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPhone_number([NotNull] sdpParser.Phone_numberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.phone_number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPhone_number([NotNull] sdpParser.Phone_numberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.phone"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPhone([NotNull] sdpParser.PhoneContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.phone"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPhone([NotNull] sdpParser.PhoneContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.connection_address"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConnection_address([NotNull] sdpParser.Connection_addressContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.connection_address"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConnection_address([NotNull] sdpParser.Connection_addressContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.bwtype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBwtype([NotNull] sdpParser.BwtypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.bwtype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBwtype([NotNull] sdpParser.BwtypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.bandwidth"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBandwidth([NotNull] sdpParser.BandwidthContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.bandwidth"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBandwidth([NotNull] sdpParser.BandwidthContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.start_time"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStart_time([NotNull] sdpParser.Start_timeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.start_time"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStart_time([NotNull] sdpParser.Start_timeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.stop_time"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStop_time([NotNull] sdpParser.Stop_timeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.stop_time"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStop_time([NotNull] sdpParser.Stop_timeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.time"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTime([NotNull] sdpParser.TimeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.time"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTime([NotNull] sdpParser.TimeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.repeat_interval"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRepeat_interval([NotNull] sdpParser.Repeat_intervalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.repeat_interval"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRepeat_interval([NotNull] sdpParser.Repeat_intervalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.typed_time"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTyped_time([NotNull] sdpParser.Typed_timeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.typed_time"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTyped_time([NotNull] sdpParser.Typed_timeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.fixed_len_time_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFixed_len_time_unit([NotNull] sdpParser.Fixed_len_time_unitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.fixed_len_time_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFixed_len_time_unit([NotNull] sdpParser.Fixed_len_time_unitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.key_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKey_type([NotNull] sdpParser.Key_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.key_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKey_type([NotNull] sdpParser.Key_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.base64"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBase64([NotNull] sdpParser.Base64Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.base64"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBase64([NotNull] sdpParser.Base64Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.base64_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBase64_unit([NotNull] sdpParser.Base64_unitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.base64_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBase64_unit([NotNull] sdpParser.Base64_unitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.base64_pad"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBase64_pad([NotNull] sdpParser.Base64_padContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.base64_pad"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBase64_pad([NotNull] sdpParser.Base64_padContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.base64_char"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBase64_char([NotNull] sdpParser.Base64_charContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.base64_char"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBase64_char([NotNull] sdpParser.Base64_charContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttribute([NotNull] sdpParser.AttributeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttribute([NotNull] sdpParser.AttributeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.att_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtt_field([NotNull] sdpParser.Att_fieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.att_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtt_field([NotNull] sdpParser.Att_fieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.att_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtt_value([NotNull] sdpParser.Att_valueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.att_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtt_value([NotNull] sdpParser.Att_valueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.media"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMedia([NotNull] sdpParser.MediaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.media"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMedia([NotNull] sdpParser.MediaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.fmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFmt([NotNull] sdpParser.FmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.fmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFmt([NotNull] sdpParser.FmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.proto"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProto([NotNull] sdpParser.ProtoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.proto"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProto([NotNull] sdpParser.ProtoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.port"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPort([NotNull] sdpParser.PortContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.port"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPort([NotNull] sdpParser.PortContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.unicast_address"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnicast_address([NotNull] sdpParser.Unicast_addressContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.unicast_address"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnicast_address([NotNull] sdpParser.Unicast_addressContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.multicast_address"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMulticast_address([NotNull] sdpParser.Multicast_addressContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.multicast_address"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMulticast_address([NotNull] sdpParser.Multicast_addressContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.ip4_multicast"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIp4_multicast([NotNull] sdpParser.Ip4_multicastContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.ip4_multicast"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIp4_multicast([NotNull] sdpParser.Ip4_multicastContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.m1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterM1([NotNull] sdpParser.M1Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.m1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitM1([NotNull] sdpParser.M1Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.ip6_multicast"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIp6_multicast([NotNull] sdpParser.Ip6_multicastContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.ip6_multicast"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIp6_multicast([NotNull] sdpParser.Ip6_multicastContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.ttl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTtl([NotNull] sdpParser.TtlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.ttl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTtl([NotNull] sdpParser.TtlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.fqdn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFqdn([NotNull] sdpParser.FqdnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.fqdn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFqdn([NotNull] sdpParser.FqdnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.ip4_address"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIp4_address([NotNull] sdpParser.Ip4_addressContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.ip4_address"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIp4_address([NotNull] sdpParser.Ip4_addressContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.b1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterB1([NotNull] sdpParser.B1Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.b1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitB1([NotNull] sdpParser.B1Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.ip6_address"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIp6_address([NotNull] sdpParser.Ip6_addressContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.ip6_address"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIp6_address([NotNull] sdpParser.Ip6_addressContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.hexpart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHexpart([NotNull] sdpParser.HexpartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.hexpart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHexpart([NotNull] sdpParser.HexpartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.hexseq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHexseq([NotNull] sdpParser.HexseqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.hexseq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHexseq([NotNull] sdpParser.HexseqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.hex4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHex4([NotNull] sdpParser.Hex4Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.hex4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHex4([NotNull] sdpParser.Hex4Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.extn_addr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtn_addr([NotNull] sdpParser.Extn_addrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.extn_addr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtn_addr([NotNull] sdpParser.Extn_addrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterText([NotNull] sdpParser.TextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitText([NotNull] sdpParser.TextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.byte_string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterByte_string([NotNull] sdpParser.Byte_stringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.byte_string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitByte_string([NotNull] sdpParser.Byte_stringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.non_ws_string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNon_ws_string([NotNull] sdpParser.Non_ws_stringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.non_ws_string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNon_ws_string([NotNull] sdpParser.Non_ws_stringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.token_char"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterToken_char([NotNull] sdpParser.Token_charContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.token_char"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitToken_char([NotNull] sdpParser.Token_charContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterToken([NotNull] sdpParser.TokenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitToken([NotNull] sdpParser.TokenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.email_safe"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmail_safe([NotNull] sdpParser.Email_safeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.email_safe"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmail_safe([NotNull] sdpParser.Email_safeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInteger([NotNull] sdpParser.IntegerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInteger([NotNull] sdpParser.IntegerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.alpha_numeric"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAlpha_numeric([NotNull] sdpParser.Alpha_numericContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.alpha_numeric"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAlpha_numeric([NotNull] sdpParser.Alpha_numericContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.pos_digit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPos_digit([NotNull] sdpParser.Pos_digitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.pos_digit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPos_digit([NotNull] sdpParser.Pos_digitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.decimal_uchar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecimal_uchar([NotNull] sdpParser.Decimal_ucharContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.decimal_uchar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecimal_uchar([NotNull] sdpParser.Decimal_ucharContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.addr_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddr_spec([NotNull] sdpParser.Addr_specContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.addr_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddr_spec([NotNull] sdpParser.Addr_specContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.local_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocal_part([NotNull] sdpParser.Local_partContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.local_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocal_part([NotNull] sdpParser.Local_partContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.domain"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDomain([NotNull] sdpParser.DomainContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.domain"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDomain([NotNull] sdpParser.DomainContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.domain_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDomain_literal([NotNull] sdpParser.Domain_literalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.domain_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDomain_literal([NotNull] sdpParser.Domain_literalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.dtext"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDtext([NotNull] sdpParser.DtextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.dtext"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDtext([NotNull] sdpParser.DtextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.atext"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtext([NotNull] sdpParser.AtextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.atext"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtext([NotNull] sdpParser.AtextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtom([NotNull] sdpParser.AtomContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtom([NotNull] sdpParser.AtomContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.dot_atom_text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDot_atom_text([NotNull] sdpParser.Dot_atom_textContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.dot_atom_text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDot_atom_text([NotNull] sdpParser.Dot_atom_textContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.dot_atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDot_atom([NotNull] sdpParser.Dot_atomContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.dot_atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDot_atom([NotNull] sdpParser.Dot_atomContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.specials"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpecials([NotNull] sdpParser.SpecialsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.specials"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpecials([NotNull] sdpParser.SpecialsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.qtext"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQtext([NotNull] sdpParser.QtextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.qtext"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQtext([NotNull] sdpParser.QtextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.qcontent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQcontent([NotNull] sdpParser.QcontentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.qcontent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQcontent([NotNull] sdpParser.QcontentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.quoted_string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuoted_string([NotNull] sdpParser.Quoted_stringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.quoted_string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuoted_string([NotNull] sdpParser.Quoted_stringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.word"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWord([NotNull] sdpParser.WordContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.word"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWord([NotNull] sdpParser.WordContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.phrase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPhrase([NotNull] sdpParser.PhraseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.phrase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPhrase([NotNull] sdpParser.PhraseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.quoted_pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuoted_pair([NotNull] sdpParser.Quoted_pairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.quoted_pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuoted_pair([NotNull] sdpParser.Quoted_pairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.fws"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFws([NotNull] sdpParser.FwsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.fws"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFws([NotNull] sdpParser.FwsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.ctext"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCtext([NotNull] sdpParser.CtextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.ctext"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCtext([NotNull] sdpParser.CtextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.ccontent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCcontent([NotNull] sdpParser.CcontentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.ccontent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCcontent([NotNull] sdpParser.CcontentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComment([NotNull] sdpParser.CommentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComment([NotNull] sdpParser.CommentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.cfws"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCfws([NotNull] sdpParser.CfwsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.cfws"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCfws([NotNull] sdpParser.CfwsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.obs_ctext"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObs_ctext([NotNull] sdpParser.Obs_ctextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.obs_ctext"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObs_ctext([NotNull] sdpParser.Obs_ctextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.obs_qtext"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObs_qtext([NotNull] sdpParser.Obs_qtextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.obs_qtext"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObs_qtext([NotNull] sdpParser.Obs_qtextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.obs_utext"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObs_utext([NotNull] sdpParser.Obs_utextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.obs_utext"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObs_utext([NotNull] sdpParser.Obs_utextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.obs_qp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObs_qp([NotNull] sdpParser.Obs_qpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.obs_qp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObs_qp([NotNull] sdpParser.Obs_qpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.obs_phrase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObs_phrase([NotNull] sdpParser.Obs_phraseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.obs_phrase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObs_phrase([NotNull] sdpParser.Obs_phraseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.obs_phrase_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObs_phrase_list([NotNull] sdpParser.Obs_phrase_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.obs_phrase_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObs_phrase_list([NotNull] sdpParser.Obs_phrase_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.obs_angle_addr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObs_angle_addr([NotNull] sdpParser.Obs_angle_addrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.obs_angle_addr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObs_angle_addr([NotNull] sdpParser.Obs_angle_addrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.obs_route"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObs_route([NotNull] sdpParser.Obs_routeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.obs_route"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObs_route([NotNull] sdpParser.Obs_routeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.obs_domain_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObs_domain_list([NotNull] sdpParser.Obs_domain_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.obs_domain_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObs_domain_list([NotNull] sdpParser.Obs_domain_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.obs_mbox_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObs_mbox_list([NotNull] sdpParser.Obs_mbox_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.obs_mbox_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObs_mbox_list([NotNull] sdpParser.Obs_mbox_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.obs_addr_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObs_addr_list([NotNull] sdpParser.Obs_addr_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.obs_addr_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObs_addr_list([NotNull] sdpParser.Obs_addr_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.obs_group_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObs_group_list([NotNull] sdpParser.Obs_group_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.obs_group_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObs_group_list([NotNull] sdpParser.Obs_group_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.obs_local_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObs_local_part([NotNull] sdpParser.Obs_local_partContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.obs_local_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObs_local_part([NotNull] sdpParser.Obs_local_partContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.obs_domain"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObs_domain([NotNull] sdpParser.Obs_domainContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.obs_domain"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObs_domain([NotNull] sdpParser.Obs_domainContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.obs_dtext"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObs_dtext([NotNull] sdpParser.Obs_dtextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.obs_dtext"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObs_dtext([NotNull] sdpParser.Obs_dtextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.obs_fws"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObs_fws([NotNull] sdpParser.Obs_fwsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.obs_fws"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObs_fws([NotNull] sdpParser.Obs_fwsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.obs_no_ws_ctl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObs_no_ws_ctl([NotNull] sdpParser.Obs_no_ws_ctlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.obs_no_ws_ctl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObs_no_ws_ctl([NotNull] sdpParser.Obs_no_ws_ctlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.address"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddress([NotNull] sdpParser.AddressContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.address"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddress([NotNull] sdpParser.AddressContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.mailbox"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMailbox([NotNull] sdpParser.MailboxContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.mailbox"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMailbox([NotNull] sdpParser.MailboxContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.name_addr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterName_addr([NotNull] sdpParser.Name_addrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.name_addr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitName_addr([NotNull] sdpParser.Name_addrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.angle_addr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAngle_addr([NotNull] sdpParser.Angle_addrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.angle_addr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAngle_addr([NotNull] sdpParser.Angle_addrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGroup([NotNull] sdpParser.GroupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGroup([NotNull] sdpParser.GroupContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.display_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDisplay_name([NotNull] sdpParser.Display_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.display_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDisplay_name([NotNull] sdpParser.Display_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.mailbox_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMailbox_list([NotNull] sdpParser.Mailbox_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.mailbox_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMailbox_list([NotNull] sdpParser.Mailbox_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.address_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddress_list([NotNull] sdpParser.Address_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.address_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddress_list([NotNull] sdpParser.Address_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.group_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGroup_list([NotNull] sdpParser.Group_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.group_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGroup_list([NotNull] sdpParser.Group_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.alpha"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAlpha([NotNull] sdpParser.AlphaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.alpha"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAlpha([NotNull] sdpParser.AlphaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.bit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBit([NotNull] sdpParser.BitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.bit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBit([NotNull] sdpParser.BitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.char_1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChar_1([NotNull] sdpParser.Char_1Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.char_1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChar_1([NotNull] sdpParser.Char_1Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.cr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCr([NotNull] sdpParser.CrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.cr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCr([NotNull] sdpParser.CrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.crlf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCrlf([NotNull] sdpParser.CrlfContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.crlf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCrlf([NotNull] sdpParser.CrlfContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.ctl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCtl([NotNull] sdpParser.CtlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.ctl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCtl([NotNull] sdpParser.CtlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.digit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDigit([NotNull] sdpParser.DigitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.digit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDigit([NotNull] sdpParser.DigitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.dquote"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDquote([NotNull] sdpParser.DquoteContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.dquote"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDquote([NotNull] sdpParser.DquoteContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.hexdig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHexdig([NotNull] sdpParser.HexdigContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.hexdig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHexdig([NotNull] sdpParser.HexdigContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.htab"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHtab([NotNull] sdpParser.HtabContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.htab"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHtab([NotNull] sdpParser.HtabContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.lf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLf([NotNull] sdpParser.LfContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.lf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLf([NotNull] sdpParser.LfContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.lwsp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLwsp([NotNull] sdpParser.LwspContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.lwsp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLwsp([NotNull] sdpParser.LwspContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.octet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOctet([NotNull] sdpParser.OctetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.octet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOctet([NotNull] sdpParser.OctetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.sp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSp([NotNull] sdpParser.SpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.sp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSp([NotNull] sdpParser.SpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.vchar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVchar([NotNull] sdpParser.VcharContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.vchar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVchar([NotNull] sdpParser.VcharContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.wsp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWsp([NotNull] sdpParser.WspContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.wsp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWsp([NotNull] sdpParser.WspContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.xxuri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterXxuri([NotNull] sdpParser.XxuriContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.xxuri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitXxuri([NotNull] sdpParser.XxuriContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.hier_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHier_part([NotNull] sdpParser.Hier_partContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.hier_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHier_part([NotNull] sdpParser.Hier_partContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.uri_reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUri_reference([NotNull] sdpParser.Uri_referenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.uri_reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUri_reference([NotNull] sdpParser.Uri_referenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.absolute_uri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAbsolute_uri([NotNull] sdpParser.Absolute_uriContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.absolute_uri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAbsolute_uri([NotNull] sdpParser.Absolute_uriContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.relative_ref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelative_ref([NotNull] sdpParser.Relative_refContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.relative_ref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelative_ref([NotNull] sdpParser.Relative_refContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.relative_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelative_part([NotNull] sdpParser.Relative_partContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.relative_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelative_part([NotNull] sdpParser.Relative_partContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.scheme"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScheme([NotNull] sdpParser.SchemeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.scheme"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScheme([NotNull] sdpParser.SchemeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.authority"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAuthority([NotNull] sdpParser.AuthorityContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.authority"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAuthority([NotNull] sdpParser.AuthorityContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.userinfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUserinfo([NotNull] sdpParser.UserinfoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.userinfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUserinfo([NotNull] sdpParser.UserinfoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.host"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHost([NotNull] sdpParser.HostContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.host"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHost([NotNull] sdpParser.HostContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.xport"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterXport([NotNull] sdpParser.XportContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.xport"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitXport([NotNull] sdpParser.XportContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.ip_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIp_literal([NotNull] sdpParser.Ip_literalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.ip_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIp_literal([NotNull] sdpParser.Ip_literalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.ipvfuture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIpvfuture([NotNull] sdpParser.IpvfutureContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.ipvfuture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIpvfuture([NotNull] sdpParser.IpvfutureContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.ipv6address"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIpv6address([NotNull] sdpParser.Ipv6addressContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.ipv6address"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIpv6address([NotNull] sdpParser.Ipv6addressContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.h16"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterH16([NotNull] sdpParser.H16Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.h16"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitH16([NotNull] sdpParser.H16Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.ls32"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLs32([NotNull] sdpParser.Ls32Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.ls32"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLs32([NotNull] sdpParser.Ls32Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.ipv4address"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIpv4address([NotNull] sdpParser.Ipv4addressContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.ipv4address"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIpv4address([NotNull] sdpParser.Ipv4addressContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.dec_octet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDec_octet([NotNull] sdpParser.Dec_octetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.dec_octet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDec_octet([NotNull] sdpParser.Dec_octetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.reg_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReg_name([NotNull] sdpParser.Reg_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.reg_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReg_name([NotNull] sdpParser.Reg_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPath([NotNull] sdpParser.PathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPath([NotNull] sdpParser.PathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.path_abempty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPath_abempty([NotNull] sdpParser.Path_abemptyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.path_abempty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPath_abempty([NotNull] sdpParser.Path_abemptyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.path_absolute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPath_absolute([NotNull] sdpParser.Path_absoluteContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.path_absolute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPath_absolute([NotNull] sdpParser.Path_absoluteContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.path_noscheme"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPath_noscheme([NotNull] sdpParser.Path_noschemeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.path_noscheme"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPath_noscheme([NotNull] sdpParser.Path_noschemeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.path_rootless"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPath_rootless([NotNull] sdpParser.Path_rootlessContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.path_rootless"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPath_rootless([NotNull] sdpParser.Path_rootlessContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.path_empty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPath_empty([NotNull] sdpParser.Path_emptyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.path_empty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPath_empty([NotNull] sdpParser.Path_emptyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.segment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSegment([NotNull] sdpParser.SegmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.segment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSegment([NotNull] sdpParser.SegmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.segment_nz"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSegment_nz([NotNull] sdpParser.Segment_nzContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.segment_nz"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSegment_nz([NotNull] sdpParser.Segment_nzContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.segment_nz_nc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSegment_nz_nc([NotNull] sdpParser.Segment_nz_ncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.segment_nz_nc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSegment_nz_nc([NotNull] sdpParser.Segment_nz_ncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.pchar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPchar([NotNull] sdpParser.PcharContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.pchar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPchar([NotNull] sdpParser.PcharContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuery([NotNull] sdpParser.QueryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuery([NotNull] sdpParser.QueryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.fragment_1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFragment_1([NotNull] sdpParser.Fragment_1Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.fragment_1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFragment_1([NotNull] sdpParser.Fragment_1Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.pct_encoded"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPct_encoded([NotNull] sdpParser.Pct_encodedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.pct_encoded"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPct_encoded([NotNull] sdpParser.Pct_encodedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.unreserved"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnreserved([NotNull] sdpParser.UnreservedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.unreserved"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnreserved([NotNull] sdpParser.UnreservedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.reserved"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReserved([NotNull] sdpParser.ReservedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.reserved"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReserved([NotNull] sdpParser.ReservedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.gen_delims"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGen_delims([NotNull] sdpParser.Gen_delimsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.gen_delims"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGen_delims([NotNull] sdpParser.Gen_delimsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sdpParser.sub_delims"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSub_delims([NotNull] sdpParser.Sub_delimsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sdpParser.sub_delims"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSub_delims([NotNull] sdpParser.Sub_delimsContext context);
}
